import {chromium} from '../frontend/node_modules/playwright/index.mjs';
import {mkdir, writeFile} from 'node:fs/promises';
import {join} from 'node:path';
const artifacts=process.env.REPLAY_ARTIFACT_DIR || '/tmp/purple-replay-check';
await mkdir(artifacts,{recursive:true});
import assert from 'node:assert/strict';
const base=process.env.REPLAY_URL||'http://127.0.0.1:8950';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH || undefined,headless:true,args:[]});
const context=await browser.newContext({viewport:{width:1600,height:1050},locale:'fr-FR'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));
const outbound=[];
context.on('request',r=>{if(new URL(r.url()).origin!==new URL(base).origin)outbound.push(r.url());});
page.on('websocket',ws=>{if(new URL(ws.url()).host!==new URL(base).host)outbound.push(ws.url());});
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto(base);await page.waitForFunction(()=>document.querySelector('[aria-label="Séance à charger"]')?.options.length>0);
const get=path=>page.evaluate(async path=>{const r=await fetch(path);if(!r.ok)throw Error(`${r.status} ${path}`);return r.json()},path);
const sessions=(await get('/api/replay/sessions')).sessions;
const chosen=[...sessions].reverse().find(s=>s.symbol==='NQ'&&s.source==='v2')||sessions.find(s=>s.symbol==='NQ')||sessions[0];
const idx=[...sessions].reverse().findIndex(s=>s.symbol===chosen.symbol&&s.session_start===chosen.session_start&&s.source===chosen.source);
await page.getByLabel('Séance à charger').selectOption(String(idx));
const stamp=Math.max(chosen.first_ts+60,Math.min(Date.parse(chosen.date+'T15:30:00Z')/1000,chosen.last_ts-60));await page.locator('input[type="time"]').fill(new Date(stamp*1000).toISOString().slice(11,16));const loadedResponse=page.waitForResponse(r=>r.url().endsWith('/api/replay/load')&&r.request().method()==='POST');await page.getByRole('button',{name:'Charger',exact:true}).click();assert((await loadedResponse).ok());
await page.waitForFunction(async()=>{const s=await(await fetch('/api/replay/status')).json();return s.loaded});await page.waitForFunction(()=>!document.querySelector('.market-chart__message'),{},{timeout:60000});await page.waitForTimeout(300);
const initial=await get('/api/replay/status');console.log('initial',JSON.stringify(initial));assert(initial.loaded&&!initial.playing);assert(Math.abs(initial.cursor_ts-stamp)<61);
const gamma=await get(`/api/gex/levels?symbol=NQ&from=${stamp-7200}&to=${stamp}`);assert(gamma.levels.length>0);assert(gamma.levels.every(l=>l.time<=initial.cursor_ts));
await page.getByRole('button',{name:'Lecture',exact:true}).click();await page.waitForTimeout(1500);await page.getByRole('button',{name:'Pause',exact:true}).click();assert((await get('/api/replay/status')).cursor_ts>initial.cursor_ts);
await page.getByRole('button',{name:'Indicateurs',exact:true}).click();assert(await page.getByText('Profil de séance',{exact:true}).isVisible());assert(!/Valentini|Dominance|Absorptions|Stacked/.test(await page.locator('body').innerText()));await page.getByRole('button',{name:'Fermer les indicateurs'}).click();
await page.getByRole('button',{name:'Achat',exact:true}).click();await page.getByRole('button',{name:/CONFIRMER ×/}).click();await page.waitForFunction(async()=>(await(await fetch('/api/paper/positions')).json()).positions?.length>0);
await page.getByRole('button',{name:'Tout fermer',exact:true}).click();await page.getByRole('button',{name:'Confirmer',exact:true}).click();await page.waitForFunction(async()=>(await(await fetch('/api/edge/journal')).json()).trades.length>0);
await page.getByRole('button',{name:'Journal',exact:true}).click();assert(await page.getByRole('heading',{name:'📓 Journal de trading'}).isVisible());assert((await get('/api/edge/journal')).trades.length>0);
const journal=await get('/api/journal?all=1');assert(journal.trades.length>0);assert(journal.trades.every(t=>t.source==='replay'));
await page.evaluate(async()=>{const r=await fetch('/api/journal/sessions/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:'Exercice de démonstration'})});if(!r.ok)throw Error('Session save failed');});
assert((await get('/api/journal/sessions')).sessions.length>0);
await writeFile(join(artifacts,'browser-state.json'),JSON.stringify(await context.storageState()));
await page.getByRole('button',{name:'Performance',exact:true}).click();await page.getByRole('button',{name:'Graphique',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.market-chart__message'),{},{timeout:60000});await page.waitForTimeout(300);await page.screenshot({path:join(artifacts,'desktop.png'),fullPage:true});
for(const width of [390,768,1920]){await page.setViewportSize({width,height:950});await page.waitForTimeout(100);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);if(width===390)await page.screenshot({path:join(artifacts,'mobile.png'),fullPage:true});}
const second=await browser.newContext();const other=await second.newPage();await other.goto(base);await other.waitForFunction(()=>document.querySelector('[aria-label="Séance à charger"]')?.options.length>0);assert(!(await other.evaluate(async()=>(await(await fetch('/api/replay/status')).json()).loaded)));assert.equal(await other.evaluate(async()=>(await(await fetch('/api/edge/journal')).json()).trades.length),0);
assert.deepEqual(outbound,[]);assert.deepEqual(errors,[]);await writeFile(join(artifacts,'network-check.json'),JSON.stringify({outbound,errors}));console.log(JSON.stringify({ok:true,session:chosen,checks:['sélection','lecture/pause','indicateurs autorisés','achat simulé','clôture','journal','performance','390/768/1920','isolation navigateurs'],errors}));await browser.close();
